export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';

export const ACTIVATION_LOADING = 'ACTIVATION_LOADING';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const FEEDS_LOADING = 'FEEDS_LOADING';
export const FEED_LOADING = 'FEED_LOADING';
export const ALL_FEEDS_SUCCESS = 'ALL_FEEDS_SUCCESS';
export const ALL_FEEDS_FAIL = 'ALL_FEEDS_FAIL';
export const FEED_SUCCESS = 'FEED_SUCCESS';
export const FEED_FAIL = 'FEED_FAIL';

export const CLUBS_LOADING = 'CLUBS_LOADING';
export const CLUB_LOADING = 'CLUB_LOADING';
export const ALL_CLUBS_SUCCESS = 'ALL_CLUBS_SUCCESS';
export const ALL_CLUBS_FAIL = 'ALL_CLUBS_FAIL';
export const CLUB_SUCCESS = 'CLUB_SUCCESS';
export const CLUB_FAIL = 'CLUB_FAIL';

export const LOSTANDFOUNDS_LOADING = 'LOSTANDFOUNDS_LOADING';
export const ALL_LOSTANDFOUNDS_SUCCESS = 'ALL_LOSTANDFOUNDS_SUCCESS';
export const ALL_LOSTANDFOUNDS__FAIL = 'ALL_LOSTANDFOUNDS__FAIL';
export const USER_LOSTANDFOUNDS_SUCCESS = 'USER_LOSTANDFOUNDS_SUCCESS';
export const USER_LOSTANDFOUNDS__FAIL = 'USER_LOSTANDFOUNDS__FAIL';

export const POST_MESS_SUCCESS = 'POST_MESS_SUCCESS';
export const POST_MESS_FAIL = 'POST_MESS_FAIL';
export const UPDATE_MESS_SUCCESS = 'UPDATE_MESS_SUCCESS';
export const UPDATE_MESS_FAIL = 'UPDATE_MESS_FAIL';
export const CANCEL_MESS_SUCCESS = 'CANCEL_MESS_SUCCESS';
export const CANCEL_MESS_FAIL = 'CANCEL_MESS_FAIL';